<a href="https://colab.research.google.com/github/matthewacash/north_tx_housing_market_analysis/blob/main/01_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 01_data_cleaning

### Mount Google Drive

In [ ]:
# mount google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

In [ ]:
base_path = '/content/drive/MyDrive/Colab Notebooks/NorthTexasCreditRisk'
os.chdir(base_path)

### Import Libraries

In [ ]:
import pandas as pd

### Inspect Each Dataset

In [ ]:
os.getcwd()

'/content/drive/MyDrive/Colab Notebooks/NorthTexasCreditRisk'

In [ ]:
os.listdir('data/raw')

['collin_unemployment.csv',
 'dallas_unemployment.csv',
 'denton_unemployment.csv',
 'cpi_inflation.csv',
 'mortgage_rates.csv',
 'collin_hpi.csv',
 'dallas_hpi.csv',
 'denton_hpi.csv',
 'fed_funds_rate.csv',
 'county_demographics.xlsx',
 '.ipynb_checkpoints']

#### Collin County Unemployment Dataset

In [ ]:
# loading unemployment datasets
df_collin_unemp_rate = pd.read_csv('data/raw/collin_unemployment.csv')

df_collin_unemp_rate.head(10)

  observation_date  TXCOLL5URN
0       1990-01-01         3.6
1       1990-02-01         3.8
2       1990-03-01         3.5
3       1990-04-01         3.5
4       1990-05-01         3.6
5       1990-06-01         4.0
6       1990-07-01         4.2
7       1990-08-01         4.0
8       1990-09-01         4.2
9       1990-10-01         3.8

In [ ]:
df_collin_unemp_rate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  434 non-null    object
 1   TXCOLL5URN        433 non-null    float64
dtypes: float64(1), object(1)
memory usage: 6.9+ KB

In [ ]:
df_collin_unemp_rate.columns

Index(['observation_date', 'TXCOLL5URN'], dtype='object')

In [ ]:
df_collin_unemp_rate.isnull().sum()

observation_date    0
TXCOLL5URN          1
dtype: int64

One missing value for the unemployment rate for Collin County

In [ ]:
df_collin_unemp_rate[df_collin_unemp_rate['TXCOLL5URN'].isnull()]

    observation_date  TXCOLL5URN
429       2025-10-01         NaN

Dropping one row from  Collin County unemployment csv

In [ ]:
df_collin_unemp_rate = df_collin_unemp_rate.dropna()

In [ ]:
df_collin_unemp_rate.isnull().sum()

observation_date    0
TXCOLL5URN          0
dtype: int64

In [ ]:
# convert date
df_collin_unemp_rate['observation_date'] = pd.to_datetime(df_collin_unemp_rate['observation_date'])
#sort and reset index
df_collin_unemp_rate = (df_collin_unemp_rate.sort_values('observation_date').reset_index(drop=True))

# save csv to cleaned folder
df_collin_unemp_rate.to_csv('data/cleaned/collin_unemployment_cleaned.csv', index=False)

### Dallas County Unemployment Dataset

In [ ]:
#load dallas unemployment data
df_dallas_unemp_rate = pd.read_csv('data/raw/dallas_unemployment.csv')

In [ ]:
df_dallas_unemp_rate.head(10)

  observation_date  TXDALL3URN
0       1990-01-01         5.0
1       1990-02-01         5.2
2       1990-03-01         4.8
3       1990-04-01         5.0
4       1990-05-01         5.2
5       1990-06-01         5.6
6       1990-07-01         5.6
7       1990-08-01         5.5
8       1990-09-01         5.7
9       1990-10-01         5.2

In [ ]:
df_dallas_unemp_rate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  434 non-null    object
 1   TXDALL3URN        433 non-null    float64
dtypes: float64(1), object(1)
memory usage: 6.9+ KB

In [ ]:
df_dallas_unemp_rate.columns

Index(['observation_date', 'TXDALL3URN'], dtype='object')

In [ ]:
df_dallas_unemp_rate.describe().T

            count      mean      std  min  25%  50%  75%   max
TXDALL3URN  433.0  5.496536  1.67722  3.0  4.1  5.2  6.7  12.7

Check Missing Values

In [ ]:
df_dallas_unemp_rate.isnull().sum()

observation_date    0
TXDALL3URN          1
dtype: int64

In [ ]:
df_dallas_unemp_rate[df_dallas_unemp_rate['TXDALL3URN'].isnull()]

    observation_date  TXDALL3URN
429       2025-10-01         NaN

In [ ]:
df_dallas_unemp_rate = df_dallas_unemp_rate.dropna()

In [ ]:
df_dallas_unemp_rate.duplicated().sum()

np.int64(0)

In [ ]:
# convert date
df_dallas_unemp_rate['observation_date'] = pd.to_datetime(df_dallas_unemp_rate['observation_date'])

#sort and reset index
df_dallas_unemp_rate = (df_dallas_unemp_rate.sort_values('observation_date').reset_index(drop=True))

# save csv to cleaned folder
df_dallas_unemp_rate.to_csv('data/cleaned/dallas_unemployment_cleaned.csv', index=False)

* 1 missing value in Dallas unemployment rate dropped
* Date column needs conversion
* All numeric and clean structure
* No duplicated values

### Denton County Dataset

In [ ]:
df_denton_unemp_rate = pd.read_csv('data/raw/denton_unemployment.csv')

In [ ]:
df_denton_unemp_rate.head(10)

  observation_date  TXDENT2URN
0       1990-01-01         4.1
1       1990-02-01         4.3
2       1990-03-01         3.9
3       1990-04-01         4.1
4       1990-05-01         4.1
5       1990-06-01         4.3
6       1990-07-01         4.2
7       1990-08-01         4.3
8       1990-09-01         4.2
9       1990-10-01         3.8

In [ ]:
df_denton_unemp_rate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  434 non-null    object
 1   TXDENT2URN        433 non-null    float64
dtypes: float64(1), object(1)
memory usage: 6.9+ KB

In [ ]:
df_denton_unemp_rate.columns

Index(['observation_date', 'TXDENT2URN'], dtype='object')

In [ ]:
df_denton_unemp_rate.isnull().sum()

observation_date    0
TXDENT2URN          1
dtype: int64

In [ ]:
df_denton_unemp_rate[df_denton_unemp_rate['TXDENT2URN'].isnull()]

    observation_date  TXDENT2URN
429       2025-10-01         NaN

In [ ]:
df_denton_unemp_rate = df_denton_unemp_rate.dropna()

In [ ]:
df_denton_unemp_rate.isnull().sum()

observation_date    0
TXDENT2URN          0
dtype: int64

In [ ]:
df_denton_unemp_rate.duplicated().sum()

np.int64(0)

In [ ]:
df_denton_unemp_rate.describe().T

            count      mean       std  min  25%  50%  75%   max
TXDENT2URN  433.0  4.238568  1.431108  1.6  3.3  4.0  4.9  12.1

* No missing values
* 1 missing value dropped
* Date column needs conversion
* All numeric datatypes and clean

### Converting Denton Dataset Date, Sorting, Resetting Index, and Saving to Cleaned Folder

In [ ]:
# convert date
df_denton_unemp_rate['observation_date'] = pd.to_datetime(df_denton_unemp_rate['observation_date'])
#sort and reset index
df_denton_unemp_rate = (df_denton_unemp_rate.sort_values('observation_date').reset_index(drop=True))

# save csv to cleaned folder
df_denton_unemp_rate.to_csv('data/cleaned/denton_unemployment_cleaned.csv', index=False)

### CPI Inflation Dataset

In [ ]:
#load cpi inflation dataset
df_cpi_inflation = pd.read_csv('data/raw/cpi_inflation.csv')

In [ ]:
df_cpi_inflation.head(10)

  observation_date  CPIAUCSL
0       1947-01-01     21.48
1       1947-02-01     21.62
2       1947-03-01     22.00
3       1947-04-01     22.00
4       1947-05-01     21.95
5       1947-06-01     22.08
6       1947-07-01     22.23
7       1947-08-01     22.40
8       1947-09-01     22.84
9       1947-10-01     22.91

In [ ]:
df_cpi_inflation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 952 entries, 0 to 951
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  952 non-null    object
 1   CPIAUCSL          951 non-null    float64
dtypes: float64(1), object(1)
memory usage: 15.0+ KB

In [ ]:
df_cpi_inflation.columns

Index(['observation_date', 'CPIAUCSL'], dtype='object')

In [ ]:
df_cpi_inflation.isnull().sum()

observation_date    0
CPIAUCSL            1
dtype: int64

### Identify Missing Value and Drop

In [ ]:
#finding missing or null value in cpi dataset
df_cpi_inflation[df_cpi_inflation['CPIAUCSL'].isnull()]

    observation_date  CPIAUCSL
945       2025-10-01       NaN

In [ ]:
df_cpi_inflation = df_cpi_inflation.dropna()

In [ ]:
df_cpi_inflation.isnull().sum()

observation_date    0
CPIAUCSL            0
dtype: int64

In [ ]:
#convert observation date to a datetime object, sort values, and reset index
df_cpi_inflation['observation_date'] = pd.to_datetime(df_cpi_inflation['observation_date'])

df_cpi_inflation = df_cpi_inflation.sort_values('observation_date').reset_index(drop=True)

In [ ]:
df_cpi_inflation.head()

  observation_date  CPIAUCSL
0       1947-01-01     21.48
1       1947-02-01     21.62
2       1947-03-01     22.00
3       1947-04-01     22.00
4       1947-05-01     21.95

In [ ]:
#save cleaned dataset for cpi inflation
df_cpi_inflation.to_csv('data/cleaned/cpi_inflation_cleaned.csv', index=False)

### Checking test Dataset for Observation Date

In [ ]:
test_df = pd.read_csv('data/cleaned/denton_unemployment_cleaned.csv')

test_df.head()

  observation_date  TXDENT2URN
0       1990-01-01         4.1
1       1990-02-01         4.3
2       1990-03-01         3.9
3       1990-04-01         4.1
4       1990-05-01         4.1

In [ ]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 433 entries, 0 to 432
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   TXDENT2URN  433 non-null    float64
dtypes: float64(1)
memory usage: 3.5 KB

### Mortgage Rates Dataset

In [ ]:
df_mortgage_rates = pd.read_csv('data/raw/mortgage_rates.csv')

In [ ]:
df_mortgage_rates.head()

  observation_date  MORTGAGE30US
0       1971-04-02          7.33
1       1971-04-09          7.31
2       1971-04-16          7.31
3       1971-04-23          7.31
4       1971-04-30          7.29

In [ ]:
df_mortgage_rates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2877 entries, 0 to 2876
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  2877 non-null   object
 1   MORTGAGE30US      2877 non-null   float64
dtypes: float64(1), object(1)
memory usage: 45.1+ KB

In [ ]:
df_mortgage_rates.columns

Index(['observation_date', 'MORTGAGE30US'], dtype='object')

In [ ]:
df_mortgage_rates.describe().T

               count      mean       std   min   25%   50%   75%    max
MORTGAGE30US  2877.0  7.687633  3.187845  2.65  5.47  7.23  9.24  18.63

In [ ]:
df_mortgage_rates.isnull().sum()

observation_date    0
MORTGAGE30US        0
dtype: int64

* No missing values in the mortgage dataset

In [ ]:
# convert date
df_mortgage_rates['observation_date'] = pd.to_datetime(df_mortgage_rates['observation_date'])
#sort and reset index
df_mortgage_rates = (df_mortgage_rates.sort_values('observation_date').reset_index(drop=True))

# save csv to cleaned folder
df_mortgage_rates.to_csv('data/cleaned/mortgage_rates_cleaned.csv', index=False)

### Federal Funds Rate Dataset

In [ ]:
df_fed_funds_rate = pd.read_csv('data/raw/fed_funds_rate.csv')

In [ ]:
df_fed_funds_rate.head()

  observation_date   DFF
0       1954-07-01  1.13
1       1954-07-02  1.25
2       1954-07-03  1.25
3       1954-07-04  1.25
4       1954-07-05  0.88

In [ ]:
df_fed_funds_rate.tail()

      observation_date   DFF
26246       2026-05-10  3.63
26247       2026-05-11  3.63
26248       2026-05-12  3.63
26249       2026-05-13  3.63
26250       2026-05-14  3.63

In [ ]:
df_fed_funds_rate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26251 entries, 0 to 26250
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  26251 non-null  object
 1   DFF               26251 non-null  float64
dtypes: float64(1), object(1)
memory usage: 410.3+ KB

In [ ]:
df_fed_funds_rate.describe().T

       count      mean       std   min   25%   50%   75%    max
DFF  26251.0  4.599025  3.550984  0.04  1.91  4.31  6.13  22.36

In [ ]:
df_fed_funds_rate.isnull().sum()

observation_date    0
DFF                 0
dtype: int64

In [ ]:
# convert date
df_fed_funds_rate['observation_date'] = pd.to_datetime(df_fed_funds_rate['observation_date'])
#sort and reset index
df_fed_funds_rate = (df_fed_funds_rate.sort_values('observation_date').reset_index(drop=True))

# save csv to cleaned folder
df_fed_funds_rate.to_csv('data/cleaned/fed_funds_rate_cleaned.csv', index=False)

## Housing Price Index (HPI) Datasets

### Collin HPI Dataset

In [ ]:
df_collin_hpi = pd.read_csv('data/raw/collin_hpi.csv')

In [ ]:
df_collin_hpi.head()

  observation_date  ATNHPIUS48085A
0       1975-01-01           36.17
1       1976-01-01           40.61
2       1977-01-01           43.83
3       1978-01-01           49.36
4       1979-01-01           59.18

In [ ]:
df_collin_hpi.describe().T

,count,mean,std,min,25%,50%,75%,max
ATNHPIUS48085A,51.0,121.197647,68.24108,36.17,81.575,100.0,123.135,310.46

In [ ]:
df_collin_hpi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  51 non-null     object
 1   ATNHPIUS48085A    51 non-null     float64
dtypes: float64(1), object(1)
memory usage: 948.0+ bytes

In [ ]:
df_collin_hpi.isnull().sum()

observation_date    0
ATNHPIUS48085A      0
dtype: int64

In [ ]:
# convert date
df_collin_hpi['observation_date'] = pd.to_datetime(df_collin_hpi['observation_date'])
#sort and reset index
df_collin_hpi = (df_collin_hpi.sort_values('observation_date').reset_index(drop=True))

# save csv to cleaned folder
df_collin_hpi.to_csv('data/cleaned/collin_hpi_cleaned.csv', index=False)

### Dallas HPI Dataset

In [ ]:
df_dallas_hpi = pd.read_csv('data/raw/dallas_hpi.csv')

In [ ]:
df_dallas_hpi.head()

  observation_date  ATNHPIUS48113A
0       1975-01-01           31.10
1       1976-01-01           32.46
2       1977-01-01           37.02
3       1978-01-01           43.56
4       1979-01-01           51.98

In [ ]:
df_dallas_hpi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  51 non-null     object
 1   ATNHPIUS48113A    51 non-null     float64
dtypes: float64(1), object(1)
memory usage: 948.0+ bytes

In [ ]:
df_dallas_hpi.columns

Index(['observation_date', 'ATNHPIUS48113A'], dtype='object')

In [ ]:
df_dallas_hpi.isnull().sum()

observation_date    0
ATNHPIUS48113A      0
dtype: int64

In [ ]:
# convert date
df_dallas_hpi['observation_date'] = pd.to_datetime(df_dallas_hpi['observation_date'])
#sort and reset index
df_dallas_hpi = (df_dallas_hpi.sort_values('observation_date').reset_index(drop=True))

# save csv to cleaned folder
df_dallas_hpi.to_csv('data/cleaned/dallas_hpi_cleaned.csv', index=False)

### Denton HPI Dataset

In [ ]:
df_denton_hpi = pd.read_csv('data/raw/denton_hpi.csv')

In [ ]:
df_denton_hpi.head()

  observation_date  ATNHPIUS48121A
0       1975-01-01           36.04
1       1976-01-01           35.94
2       1977-01-01           39.70
3       1978-01-01           47.79
4       1979-01-01           55.63

In [ ]:
df_denton_hpi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  51 non-null     object
 1   ATNHPIUS48121A    51 non-null     float64
dtypes: float64(1), object(1)
memory usage: 948.0+ bytes

In [ ]:
df_denton_hpi.columns

Index(['observation_date', 'ATNHPIUS48121A'], dtype='object')

In [ ]:
df_denton_hpi.isnull().sum()

observation_date    0
ATNHPIUS48121A      0
dtype: int64

In [ ]:
# convert date
df_denton_hpi['observation_date'] = pd.to_datetime(df_denton_hpi['observation_date'])
#sort and reset index
df_denton_hpi = (df_denton_hpi.sort_values('observation_date').reset_index(drop=True))

# save csv to cleaned folder
df_denton_hpi.to_csv('data/cleaned/denton_hpi_cleaned.csv', index=False)

### County Demographics Dataset

In [ ]:
df_county_demographics = pd.read_excel('data/raw/county_demographics.xlsx')

In [ ]:
df_county_demographics.head()

,county,median_household_income,poverty_rate,population,bachelors_degree_pct,homeownership_rate
0,Collin,121600,0.057,1297179,0.562,0.645
1,Dallas,76547,0.125,2661397,0.357,0.508
2,Denton,111498,0.062,1069346,0.494,0.655

In [ ]:
df_county_demographics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   county                   3 non-null      object
 1   median_household_income  3 non-null      int64
 2   poverty_rate             3 non-null      float64
 3   population               3 non-null      int64
 4   bachelors_degree_pct     3 non-null      float64
 5   homeownership_rate       3 non-null      float64
dtypes: float64(3), int64(2), object(1)
memory usage: 276.0+ bytes

In [ ]:
#fix leading/trailling whitespace in rows
df_county_demographics['county'] = df_county_demographics['county'].str.strip()

In [ ]:
df_county_demographics.head()

,county,median_household_income,poverty_rate,population,bachelors_degree_pct,homeownership_rate
0,Collin,121600,0.057,1297179,0.562,0.645
1,Dallas,76547,0.125,2661397,0.357,0.508
2,Denton,111498,0.062,1069346,0.494,0.655

In [ ]:
df_county_demographics['county'].unique()

array(['Collin', 'Dallas', 'Denton'], dtype=object)

In [ ]:
#save to cleaned file folder
df_county_demographics.to_csv('data/cleaned/county_demographics_cleaned.xlsx', index=False)